### ISSUE TITLE
CWE-502: Deserialization of Untrusted Data - TLSv1.2< SSLv2< - conf 

### ISSUE THREAD

**Issue by EvertonMelo** [jpmorganchase/tessera#925]
hello guys, I looked for checks on already outdated protocols and size keys that have already known attacks and have not found a proper handling in the default settings. 

# The problem. 

There is no secure default setting. So an attacker can deliberately create a weak configuration to intercept data. [Man-in-the-middle](https://www.cloudflare.com/learning/security/threats/man-in-the-middle-attack/)
as reported in the [RFC6176](https://tools.ietf.org/html/rfc6176#section-2) 

#### the source code vulnerable {sample}

````
    "server": {
        "port": 8080,
        "hostName": "http://localhost",
        "bindingAddress": "http://localhost:9001",
        "sslConfig": {
            **"tls": "OFF",**
            "generateKeyStoreIfNotExisted": "false",
            "serverKeyStore": "./ssl/server1-keystore",
            "serverKeyStorePassword": "quorum",
            "serverTrustStore": "./ssl/server-truststore",
            "serverTrustStorePassword": "quorum",
            "serverTrustMode": "CA",
            "clientKeyStore": "./ssl/client1-keystore",
            "clientKeyStorePassword": "quorum",
            "clientTrustStore": "./ssl/client-truststore",
            "clientTrustStorePassword": "quorum",
            "clientTrustMode": "CA",
            "knownClientsFile": "./ssl/knownClients1",
            "knownServersFile": "./ssl/knownServers1"
        }
    },
````
*reference: [in project](https://github.com/jpmorganchase/tessera/blob/master/config/src/test/resources/sample_full.json#L13)

**### Note¹:** I am aware that this is just sample code, but I found no check for weak protocols.

## verified files.

ALL 
956 directories, 1162 files

#### arquives relevent in scope:

`./cli/admin-cli/src/test/resources/sample-config.json
./cli/cli-api/src/test/resources/sample-config.json
./cli/config-cli/src/main/java/com/quorum/tessera/config/cli/DefaultCliAdapter.java
./cli/config-cli/src/main/java/com/quorum/tessera/config/cli/parsers/KeyGenerationParser.java
./cli/config-cli/src/test/java/com/quorum/tessera/config/cli/OverrideUtilTest.java
./cli/config-cli/src/test/java/com/quorum/tessera/config/cli/parsers/KeyGenerationParserTest.java
./cli/config-cli/src/test/resources/keygen-sample.json
./cli/config-cli/src/test/resources/keytests/passwordsMissing.json
./cli/config-cli/src/test/resources/keytests/passwordsWrong.json
./cli/config-cli/src/test/resources/keytests/pubPrivInlineLocked.json
./cli/config-cli/src/test/resources/keytests/pubPrivInlineUnlocked.json
./cli/config-cli/src/test/resources/keytests/pubPrivPasswordsFile.json
./cli/config-cli/src/test/resources/keytests/pubPrivUsingPathsLocked.json
./cli/config-cli/src/test/resources/keytests/pubPrivUsingPathsUnlocked.json
./cli/config-cli/src/test/resources/keytests/pubPrivUsingPathsUnlocked_missingPrivateKey.json
./cli/config-cli/src/test/resources/keytests/pubPrivUsingPathsUnlocked_missingPublicKey.json
./cli/config-cli/src/test/resources/sample-config-invalidpath.json
./cli/config-cli/src/test/resources/sample-config.json
./config-migration/src/main/java/com/quorum/tessera/config/builder/ConfigBuilder.java
./config-migration/src/main/java/com/quorum/tessera/config/migration/LegacyCliAdapter.java
./config-migration/src/main/java/com/quorum/tessera/config/migration/LegacyOverridesMixin.java
./config-migration/src/main/java/com/quorum/tessera/config/migration/TomlConfigFactory.java
./config-migration/src/test/java/com/quorum/tessera/config/builder/ConfigBuilderTest.java
./config-migration/src/test/java/com/quorum/tessera/config/migration/LegacyCliAdapterTest.java
./config-migration/src/test/java/com/quorum/tessera/config/migration/test/FixtureUtil.java
./config-migration/src/test/java/com/quorum/tessera/config/migration/TomlConfigFactoryTest.java
./config-migration/src/test/resources/sample-all-values.conf
./config-migration/src/test/resources/sample.conf
./config-migration/src/test/resources/sample-no-keys.conf
./config-migration/src/test/resources/sample-toml-no-nulls.conf
./config-migration/src/test/resources/sample-toml-no-nulls-tls-off.conf
./config-migration/src/test/resources/sample-with-only-private-keys.conf
./config-migration/src/test/resources/sample-with-only-public-keys.conf
./config/src/main/java/com/quorum/tessera/config/constraints/SslConfigValidator.java
./config/src/main/java/com/quorum/tessera/config/HashicorpKeyVaultConfig.java
./config/src/main/java/com/quorum/tessera/config/InfluxConfig.java
./config/src/main/java/com/quorum/tessera/config/ServerConfig.java
./config/src/main/java/com/quorum/tessera/config/SslConfig.java
./config/src/test/java/com/quorum/tessera/config/constraints/SslConfigValidatorTest.java
./config/src/test/java/com/quorum/tessera/config/HashicorpKeyVaultConfigTest.java
./config/src/test/java/com/quorum/tessera/config/InfluxConfigTest.java
./config/src/test/java/com/quorum/tessera/config/ServerConfigTest.java
./config/src/test/resources/keypassupdate/newLockedKeyAddInline.json
./config/src/test/resources/keypassupdate/newLockedKeyAddInlineWithExisting.json
./config/src/test/resources/keypassupdate/newLockedKeyAddToFile.json
./config/src/test/resources/keypassupdate/newLockedKeyNoPasswordsSet.json
./config/src/test/resources/keypassupdate/newLockedKeyWithUnlockedPrevious.json
./config/src/test/resources/keypassupdate/nullKeys.json
./config/src/test/resources/mask-fixture.json
./config/src/test/resources/mask-fixture-with-private-key-path.json
./config/src/test/resources/sample_full.json
./config/src/test/resources/sample.json
./config/src/test/resources/sample-private-keygen.json
./.git/index
./.git/objects/pack/pack-258a9f17f6b04ecf1915b60c870b51a87ef57947.idx
./.git/objects/pack/pack-258a9f17f6b04ecf1915b60c870b51a87ef57947.pack
./harquives.txt
./key-vault/hashicorp-key-vault/src/main/java/com/quorum/tessera/key/vault/hashicorp/HashicorpKeyVaultServiceFactoryUtil.java
./key-vault/hashicorp-key-vault/src/test/java/com/quorum/tessera/key/vault/hashicorp/HashicorpKeyVaultServiceFactoryUtilTest.java
./README.md
./security/src/main/java/com/quorum/tessera/ssl/context/ClientSSLContextFactoryImpl.java
./security/src/main/java/com/quorum/tessera/ssl/context/ServerSSLContextFactoryImpl.java
./security/src/main/java/com/quorum/tessera/ssl/context/SSLContextBuilder.java
./security/src/main/java/com/quorum/tessera/ssl/util/TlsUtils.java
./security/src/test/java/com/quorum/tessera/ssl/context/SSLContextBuilderTest.java
./security/src/test/java/com/quorum/tessera/ssl/util/TlsUtilsTest.java
./tessera-core/src/test/resources/config1.json
./tessera-core/src/test/resources/config-with-relay.json
./tests/acceptance-test/src/test/java/com/quorum/tessera/test/migration/config/ConfigMigrationSteps.java
./tests/acceptance-test/src/test/java/com/quorum/tessera/test/vault/hashicorp/HashicorpStepDefs.java
./tests/acceptance-test/src/test/resources/features/vault/hashicorp.feature
./tests/acceptance-test/src/test/resources/legacy.toml
./tests/acceptance-test/src/test/resources/vault/hashicorp-tls-config.hcl
./tests/acceptance-test/src/test/resources/vault/tessera-hashicorp-approle-config.json
./tests/acceptance-test/src/test/resources/vault/tessera-hashicorp-config.json
`

#### How to fix it, suggestion 
1 - check the protocol when establishing the connection. 
2 - use keys longer than 64 bits. 
3 - Disable TLSv1, TLSv1.1 and SSLv1

**Comment by namtruong** [comment]
Hi, thanks for raising this.

In Tessera we use Jetty for our servers, which during initialisation the default protocol offered is TLSv1.2 (if ssl is enabled). Old protocols such as TLSv1, TLSv1.1, SSLv2, SSLv3 are no longer supported by default. And in our case a Tessera client only establishes connections to a Tessera server (a different Tessera node). So I don't think RFC6176 applies in this case.

The code snippet posted above is just a sample configuration file to demonstrate the json structure - it has ssl switched off.

About the key size - could you please elaborate - which keys are you referring to?

**Comment by cucrisis** [comment]
Hi @EvertonMelo thanks for your report. We believe there is no Deserialization of Untrusted Data issue present in reported scope. The config file you reference is an example config file, and it's not the default configuration. When TLS is enabled by default TLSv1, TLSv1.1 and SSLv1 are disabled. However if "TLS" entry is not present in the config file the default is to have it disabled, which is something we will change.  The key size we use for all our ciphers are more than 64bits. 

**Note:** for the disclosure of security vulnerability please use our responsible disclosure channel.

**Comment by EvertonMelo** [comment]
@namtruong  @cucrisis 

I understand what was said by you, but as I listed the files there is no such verification, so someone can loosen the communication so that it is interceptable. 

RFC reports major flaws, but not the only ones without a protocol version and key length check, there are several versions of TLS that are backward compatible. This can be a much bigger problem.

to get out of the field of theory, give me an IP of a test node, so I can bring more data from an environment controlled by you,

so we have more data to corroborate what you said.

**note¹:** not using encrypted email to receive bugs, is to say that emails are not necessary, as emails can be changed there is no way to verify the integrity of the sent data.

**note²**: [Open/PGP eazy](https://medium.com/swlh/secure-your-emails-in-5-minutes-using-pgp-5435ba007b3b)

**Comment by cucrisis** [comment]
Please use the following guide to spin up a test net for your Graybox testing. 
https://docs.goquorum.com/en/latest/Getting%20Started/Creating-A-Network-From-Scratch 

If there is any Unsafe Deserialization or insecure transport Protocol / Protocol configuration is being used we would like to know about it, however at the moment we are unable to confirm the risk, i am more than happy to chat about this further over our slack - http://bit.ly/quorum-slack.
